---
# tasks file for roles/web_role

- name: Install Apache
  apt:
    name: apache2
    state: present
  become: yes

- name: Install PHP
  apt:
    name: php
    state: present
  become: yes

- name: Install PHP MySQL
  apt:
    name: php-mysql
    state: present
  become: yes

- name: Start and enable Apache service
  service:
    name: apache2
    state: started
    enabled: yes
  become: yes
